### ISSUE TITLE
Truncated TAR archive fails to extract 

### ISSUE THREAD

**Issue by vlaci** [IoT-Inspector/unblob#156]
Related to #118 and can be seen on files contained in the referenced firmware.

A file containing partial TAR archive fails to extract with:
```
Traceback (most recent call last):
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/finder.py", line 81, in search_chunks_by_priority
    chunk = handler.calculate_chunk(limited_reader, real_offset)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/archive/tar.py", line 100, in calculate_chunk
    end_offset = _get_tar_end_offset(file)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/archive/tar.py", line 20, in _get_tar_end_offset
    last_offset = _get_end_of_last_tar_entry(file)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/archive/tar.py", line 28, in _get_end_of_last_tar_entry
    last_member = tf.getmembers()[-1]
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/tarfile.py", line 1799, in getmembers
    self._load()        # all members, we first have to
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/tarfile.py", line 2397, in _load
    tarinfo = self.next()
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/tarfile.py", line 2321, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data
```
If there are multiple records in the file, it makes sense to just rewind to the last non-corrupt one.

**Comment by QKaiser** [comment]
If the tar file is _really_ truncated, we end up with this:

```
Traceback (most recent call last):
  File "/home/quentin/unblob/unblob/finder.py", line 74, in search_chunks_by_priority
    chunk = handler.calculate_chunk(limited_reader, real_offset)
  File "/home/quentin/unblob/unblob/handlers/archive/tar.py", line 100, in calculate_chunk
    end_offset = _get_tar_end_offset(file)
  File "/home/quentin/unblob/unblob/handlers/archive/tar.py", line 20, in _get_tar_end_offset
    last_offset = _get_end_of_last_tar_entry(file)
  File "/home/quentin/unblob/unblob/handlers/archive/tar.py", line 28, in _get_end_of_last_tar_entry
    last_member = tf.getmembers()[-1]
IndexError: list index out of range
```

We must make sure members is not empty.
