### ISSUE TITLE
Chunks with extreme offset cause ValueError

### ISSUE THREAD

**Issue by vlaci** [IoT-Inspector/unblob#211]
I guess we could further stricten our sanity checks to disallow chunks having greater than (1<<63)-1 offsets.
The offending chunks comes from the yaffs handler:

```
Traceback (most recent call last):
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/finder.py", line 74, in search_chunks_by_priority
    chunk = handler.calculate_chunk(limited_reader, real_offset)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/filesystem/yaffs.py", line 148, in calculate_chunk
    files, offset = self.get_files(file, start_offset, config)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/filesystem/yaffs.py", line 105, in get_files
    file.seek(current_offset, io.SEEK_SET)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/file_utils.py", line 215, in seek
    new_pos = self._file.seek(offset, whence)
ValueError: cannot fit 'int' into an offset-sized integer
```

**Comment by QKaiser** [comment]
Let's implement the sanity check in `LimitedStartReader` and raise a ValueError when that happens (or something else ?).

Can you send me the yaffs sample ? I'd like to double check if there's an issue with the yaffs handler (working theory: current_offset can be the unmasked addition of two uint64 which is larger than uint64).
