### ISSUE TITLE
failed to extract lzma compressed kernel and initrd cpio

### ISSUE THREAD

**Issue by martonilles** [IoT-Inspector/unblob#253]
From the bellow firmware unblob can not extract the lzma compressed object at beginning
https://fw.gl-inet.com/firmware/mt300n-v2/v1/openwrt-mt300n-v2-3.105.bin

Also get an error:
```
Traceback (most recent call last):
  File "/home/marci/src/iot/unblob/unblob/handlers/compression/lzma.py", line 52, in calculate_chunk
    read_size += len(decompressor.decompress(data))
_lzma.LZMAError: Corrupt input data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marci/src/iot/unblob/unblob/finder.py", line 75, in search_chunks_by_priority
    chunk = handler.calculate_chunk(limited_reader, real_offset)
  File "/home/marci/src/iot/unblob/unblob/handlers/compression/lzma.py", line 55, in calculate_chunk
    raise InvalidInputFormat from exc
unblob.file_utils.InvalidInputFormat
```

**Comment by QKaiser** [comment]
We need to adjust the LZMA signature. The LZMA stream starts with "6d" rather than "5d":

````
head -c 128 /tmp/openwrt-mt300n-v2-3.105.bin| hexdump -C
00000000  27 05 19 56 15 ef a0 fd  5b 75 2c f3 00 17 91 4a  |'..V....[u,....J|
00000010  80 00 00 00 80 00 00 00  6e b2 09 c4 05 05 02 03  |........n.......|
00000020  4d 49 50 53 20 4f 70 65  6e 57 72 74 20 4c 69 6e  |MIPS OpenWrt Lin|
00000030  75 78 2d 34 2e 31 34 2e  36 33 00 00 00 00 00 00  |ux-4.14.63......|
00000040  6d 00 00 20 00 bc 5e 4a  00 00 00 00 00 00 00 6f  |m.. ..^J.......o| <- LZMA stream at offset 0x40
````

We're actually missing on a lot of potential LZMA streams right now. If we follow the algorithm in section 1.1.1 of https://svn.python.org/projects/external/xz-5.0.3/doc/lzma-file-format.txt, these are valid LZMA properties fields:

```
( 51 | 5A | 5B | 5C | 5D | 5E | 63 | 64 | 65 | 66 | 6C | 6D | 6E | 75 | 76 | 7E | 87 | 88 | 89 | 8A | 8B | 90 | 91 | 92 | 93 | 99 | 9A | 9B | A2 | A3 | AB | B4 | B5 | B6 | B7 | B8 | BD | BE | BF | C0 | C6 | C7 | C8 | CF | D0 | D8 )
```

We have to adjust the LZMA handler.

**Comment by QKaiser** [comment]
Note that the file itself starts with a uImage, which we plan on supporting at some point :)
