### ISSUE TITLE
Relative path logging bug

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#90]
unblob fails when receiving a path outside its own root:

```
poetry run unblob -v /tmp/lzo     
2021-12-03 10:35.22 [info     ] Start processing files         count=0x1
2021-12-03 10:35.22 [info     ] Start processing file          path=/tmp/lzo
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/quentin/unblob/unblob/cli.py", line 54, in main
    cli.invoke(ctx)
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/quentin/unblob/unblob/cli.py", line 41, in cli
    process_file(path.parent, path, extract_root, max_depth=depth)
  File "/home/quentin/unblob/unblob/processing.py", line 28, in process_file
    log.info("Found directory")
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/structlog/_log_levels.py", line 118, in meth
    return self._proxy_to_logger(name, event, **kw)
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/structlog/_base.py", line 202, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/structlog/_base.py", line 159, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/home/quentin/unblob/unblob/logging.py", line 31, in convert_type
    rel_path = value.relative_to(extract_root)
  File "/usr/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/tmp/lzo' does not start with '/home/quentin/unblob'
```

We should fix it here https://github.com/IoT-Inspector/unblob/blob/main/unblob/logging.py#L31

Assigning it to @kissgyorgy given that he worked on f565ed2b03d1ff0cfbee16a7b6dedb2196f9f6c8, which looks similar.

**Comment by kissgyorgy** [comment]
We just fixed this with János, the PR is in progress.
